// generated by go:generate version; DO NOT EDIT
package flags

import (
	"flag"
	"fmt"
)

func init() {
	var version bool

	flag.BoolVar(&version, "version", false, "print application version and build info")

	flag.Parse()

	if version {
		fmt.Println(`
You append 'version' argument, but something must done to show version:

1. env $GOBIN must be set, and must append it to $PATH.
   example:
    export GOPATH=/opt/gowork
    export GOBIN=$GOPATH/bin
    export PATH=$PATH:$GOBIN
2. run 'go generate' before build.
3. run '<appname> -version', application version and build info will printed.
        `)
	}
}
