package master

var commonURLArr = []string{
	"/master/trade/query",
	"/master/trade/report",
	"/master/trade/stat",
	"/master/trade/stat/report",
	"/master/trade/findOne",
	"/master/user/updatePwd",
	"/master/app/locale",
	"/master/list",
	"/master/trade/settle/report",
	"/master/trade/settle/journal",
	"/master/excrat/query",
	"/master/excrat/create",
}

var genAdminURLArr = []string{
	"/master/trade/query",
	"/master/trade/report",
	"/master/trade/stat",
	"/master/trade/stat/report",
	"/master/trade/findOne",
	"/master/user/updatePwd",
	"/master/trade/settle/report",
	"/master/trade/message",
	"/master/agent/find",
	"/master/qiniu/download",
	"/master/app/locale",
	"/master/list",
	"/master/trade/settle/report",
	"/master/trade/settle/journal",
	"/master/excrat/query",
	"/master/excrat/create",
}

var agentURLArr = []string{
	"/master/user/find",
	"/master/user/update",
	"/master/user/updatePwd",
	"/master/user/resetPwd",
	"/master/trade/query",
	"/master/trade/report",
	"/master/trade/stat",
	"/master/trade/stat/report",
	"/master/trade/findOne",
	"/master/user/updatePwd",
	"/master/app/locale",
	"/master/app/resetPwd",
	"/master/list",
	"/master/trade/settle/report",
	"/master/trade/settle/journal",
	"/master/excrat/query",
	"/master/excrat/create",
}
