#!/bin/bash

set -e

pkg="github.com/CardInfoLink/quickpay"
pwd
path=$GOPATH/src/$pkg

cd $path

#echo post-merge

# auto update
cp .hooks/* .git/hooks/

# rm -r static/app/bower_components/
# ./publish.sh dev

exit 0
