#!/bin/bash

set -e

pkg="github.com/CardInfoLink/quickpay"

path=$GOPATH/src/$pkg

cd $path

#echo post-merge

# auto update
cp .hooks/* .git/hooks/

# 依赖更新，重新拉取
# rm -r static/app/bower_components/
# ./publish.sh dev

exit 0
