#!/bin/bash

set -e

pkg="github.com/CardInfoLink/quickpay"

path=$GOPATH/src/$pkg

cd $path
#pwd

#echo post-merge

# auto update
cp .hooks/* .git/hooks/

rm -r static/bower_components/
./publish.sh dev

exit 0
