#!/bin/bash

set -e

pkg="github.com/CardInfoLink/quickpay"

path=$GOPATH/src/$pkg

cd $path

# git pull cil develop
#
# if [ $? -ne 0 ]; then
#     echo 'use "git status && git add <file> && git commit -m <message>" before push'
#     exit 1
# fi

# 依赖更新，重新拉取
rm -r static/app/bower_components/
./publish.sh dev

exit 0
