#!/bin/bash

set -e

pkg="github.com/CardInfoLink/quickpay"

path=$GOPATH/src/$pkg

cd $path

#cp .hooks/* .git/hooks/

git pull cil develop

if [ $? -ne 0 ]; then
    echo 'use "git status && git add <file> && git commit -m <message>" before push'
    exit 1
fi

rm -rf static/bower_components
./publish.sh dev

exit 0
