{
    "Currency": "TWD",
    "ChanCode": {
        "ALP": "支付寶",
        "WXP": "微信",
        "Unknown": "未知"
    },
    "ReportName": {
        "SettleJournal": "對帳單",
        "SettleSummary": "匯總清算檔案"
    },
    "Role": {
        "Company": "公司",
        "Agent": "代理",
        "Group": "商戶",
        "Mer": "門店"
    },
    "BusicdType": {
        "Purc": "下單並支付",
        "Paut": "預下單",
        "Inqy": "査詢",
        "Refd": "退款",
        "Void": "撤銷",
        "Canc": "取消",
        "Qyzf": "企業付款",
        "Jszf": "公眾號支付",
        "Veri": "卡券核銷",
        "Unknown": "未知"
    },
    "TransStatus": {
        "TransHandling": "交易處理中",
        "TransFail": "交易失敗",
        "TransSuccess": "交易成功",
        "TransClosed": "交易已退款",
        "Unknown": "未知"
    },
    "StatReport": {
        "Title": "商戶交易報表匯總",
        "Total": "總計：",
        "StartDate": "開始日期：",
        "EndDate": "結束日期：",
        "Remark": "注：手續費為每筆單筆計算後四捨五入精確到分，跟總額計算手續費略有誤差.",
        "MerId": "商戶號",
        "MerName": "商戶名稱",
        "Summary": "匯總",
        "ALP": "支付寶",
        "WXP": "微信",
        "AgentName": "代理名稱",
        "TotalCount": "總筆數",
        "TotalAmt": "總金額",
        "Count": "筆數",
        "Amt": "金額",
        "Fee": "手續費"
    },
    "TransReport": {
        "SheetName": "商戶交易報表",
        "MerId": "商戶號",
        "MerName": "商戶名稱",
        "OrderNum": "訂單號",
        "TransAmt": "交易金額",
        "TransCurr": "交易幣種",
        "MerFee": "商戶手續費",
        "ChanCode": "通路",
        "TransTime": "交易時間",
        "PayTime": "支付時間",
        "TransStatus": "交易狀態",
        "ChanMerId": "通路商戶號",
        "AgentCode": "機构",
        "TerminalId": "終端號",
        "Busicd": "交易類型",
        "OrigOrderNum": "原訂單號",
        "Remark": "備註",
        "IsSettled": "是否參與清算",
        "RefundAmt": "退款金額",
        "Fee": "手續費",
        "SettAmt": "清算金額",
        "TotalTransAmt": "交易總額",
        "TotalRefundAmt": "退款總額",
        "TotalFee": "手續費總額",
        "TotalSettAmt": "清算總額",
        "Yes": "是",
        "No": "否"
    },
    "ImportMessage": {
        "Yes": "是",
        "No": "否",
        "SysErr": "系統錯誤，請重新上傳。",
        "EmptyErr": "上傳表格為空，請檢查。",
        "FileErr": "無法獲取檔案，請重新上傳。",
        "CellMapErr": "%d 行：%s",
        "ColNumErr": "列數有誤，實際應為 %d 行，讀取到 %d 行。具體資訊為：%s",
        "ImportSuccess": "成功處理 %d 行數據，耗時 %s。",
        "MerIdRepeat": "門店號(%s)重複",
        "DataHandleErr": {
            "NotSupportOperation": "第 %d 行，暫不支持 %s 操作。",
            "NoMerId": "第 %d 行，門店號為空",
            "MerIdFormatErr": "第 %d 行，門店號 %s 格式錯誤",
            "MerIdExist": "門店：%s 已存在",
            "MerIdNotExist": "門店：%s 不存在",
            "ALPMerchantErr": "支付寶商戶(%s): %s",
            "WXPMerchantErr": "微信商戶(%s): %s",
            "UsernameExist": "門店：%s 帳戶資訊-用戶名：%s 已存在",
            "UsernameNotExist": "門店：%s 帳戶資訊-用戶名：%s 不存在",
            "AgentNotExist": "門店：%s 代理程式碼（%s）不存在",
            "CompanyNotExist": "門店：%s 公司程式碼（%s）不存在",
            "CompanyBelongsErr": "門店：%s 公司程式碼(%s)不屬於該代理",
            "GroupNotExist": "門店：%s 商戶程式碼(%s)不存在",
            "GroupBelongsErr": "門店：%s 商戶程式碼(%s)不屬於該代理",
            "NoALPKey": "支付寶商戶：%s 金鑰為空",
            "NoALPRouteToUdpSf": "沒找到門店：%s，對應的支付寶商戶，無法變更清算標識。",
            "NoWXPRouteToUdpSf": "沒找到門店：%s，對應的微信商戶，無法變更清算標識。",
            "WXPNotAgentMode": "微信商戶：%s 並不是受理商模式",
            "SysConfigErr": "系統錯誤配寘，請聯系管理員。",
            "AgentMerInfoErr": "微信商戶：%s 代理商商戶號填寫錯誤，應為 %s，實際為 %s",
            "AgentModeNotMatch": "微信商戶：%s 為受理商模式",
            "NoSuchAgentMer": "微信商戶：%s 系統中沒有程式碼為 %s 的代理商商戶",
            "NoWXPKey": "微信商戶：%s 金鑰為空",
            "CILFeeErr": "訊聯跟通路費率格式錯誤(%s)",
            "MerFeeErr": "商戶跟訊聯費率格式錯誤(%s)",
            "CILFeeOverMax": "訊聯跟通路費率超過最大值 3% (%s)",
            "MerFeeOverMax": "商戶跟訊聯費率超過最大值 3% (%s)"
        },
        "ValidateErr": {
            "NoMerName": "門店：%s 門店名稱為空",
            "NoSignKey": "門店：%s 開啟驗簽需要填寫簽名金鑰",
            "NoAgentCode": "門店：%s 代理程式碼為空",
            "OpenSignValueErr": "是否開啟驗簽：%s 取值錯誤，應為【是】或【否】",
            "AddAcctValueErr": "是否新增帳戶資訊：%s 取值錯誤，應為【是】或【否】",
            "UNOrPWDEmptyErr": "門店：%s 新增帳戶資訊用戶名或密碼為空",
            "SignLengthErr": "門店：%s 簽名金鑰長度錯誤(%s)",
            "NoCommodityName": "門店：%s 商品名稱為空",
            "IsAgentStrErr": "是否代理商模式：%s 取值錯誤，應為【是】或【否】",
            "NoWXPMer": "門店：%s 代理商模式需要填寫微信商戶號",
            "WXPSettFlagErr": "微信商戶清算標識：%s 取值錯誤，应为[CIL,CHANNEL,AGENT,COMPANY,GROUP]",
            "ALPSettFlagErr": "支付寶商戶清算標識：%s 取值錯誤，应为[CIL,CHANNEL,AGENT,COMPANY,GROUP]",
            "NoOverseasChanMer": "門店：%s 支付寶境外商戶必須填寫 merchant_name 和 merchant_no",
            "NoSchemeType": "門店：%s 支付寶境外商戶必須填寫計費方案"
        }
    },
    "Merchant": {
        "Title": "商戶表",
        "MerId": "商戶號",
        "MerName": "商戶名稱",
        "IsNeedSign": "是否驗簽",
        "SignKey": "簽名密鑰",
        "BillUrl": "賬單鏈接",
        "PayUrl": "支付鏈接",
        "Yes": "是",
        "No": "否"
    }
}
